boom/urls.py
from django.urls import path
from . import views


app_name='boom'

urlpatterns=[
    path('login',views.signin, name='login'),
    path('logout_user',views.logout_user,name='logout-user'),
    path('signup',views.signup, name='signup'),
    path('', views.index, name='index'),
    path('(?P<album_id>[0-9]+)/' ,views.detail, name='info'),
    path('new-album',views.create_album, name='create-album'),
    path('<int:pk>/album-update', views.AlbumUpdateView.as_view(), name='album-update'),
    path('(?P<album_id>[0-9]+)/delete-album', views.album_delete, name='album-delete'),
    path('(?P<album_id>[0-9]+)/new-song',views.create_song, name='create-song'),
    path('<int:pk>/update-song', views.SongUpdateView.as_view(), name='update-song'),
    path('(?P<album_id>[0-9]+)/delete-song/((?P<song_id>[0-9]+)',views.delete_song, name='song-delete'),

]

music/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('boom.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boom/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User

# Create your models here.
class Album(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    album_name=models.CharField(max_length=25)
    artist_name=models.CharField(max_length=30)
    artist_genre=models.CharField(max_length=10)
    album_cover=models.FileField()


    def get_absolute_url(self):
        return reverse('boom/index.html')


class Song(models.Model):
    album=models.ForeignKey(Album, on_delete=models.CASCADE)
    song_name=models.CharField(max_length=25)
    song_audio=models.FileField()

    def __str__(self):
        return self.song_name
    def get_absolute_url(self):
        return reverse('boom:info', args=[(self.pk)])

boom/forms.py
from django import forms
from .models import Album, Song
from django.contrib.auth.models import User

class AlbumForm(forms.ModelForm):
    class Meta:
        model=Album
        fields=['album_name','artist_name','artist_genre','album_cover',]

class SongForm(forms.ModelForm):
    class Meta:
        model=Song
        fields=['song_name','song_audio']

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)

    class Meta:

        model=User
        fields=['username','email','password']

boom/views.py
from django.shortcuts import render,get_object_or_404,redirect
from . models import Album,Song
from . forms import AlbumForm,SongForm,UserForm
from django.views.generic import UpdateView,DeleteView
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.decorators import login_required
from django.db.models import Q
# Create your views here.
@login_required(login_url='boom:login')
def index(request):
    albums = Album.objects.filter(user=request.user)
    song_results=Song.objects.all()
    query=request.GET.get("q")
    if query:
        albums= albums.filter(
            Q(album_name__icontains=query)|
            Q(artist_name__icontains=query)
        ).distinct()
        song_results=song_results.filter(
            Q(song_name__icontains=query)
        ).distinct()
        return render(request,'music/index.html',{'albums':albums})
    return render(request,'music/index.html',{'albums':albums,'songs':song_results})



def detail(request,album_id):
    album=get_object_or_404(Album,pk=album_id)
    return render(request,'music/info.html',{'album':album})

def create_album(request):
    form = AlbumForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        albums = Album.objects.filter(user=request.user)
        for album in albums:
            if album.album_name==form.cleaned_data.get('album_name'):
                context={
                    'form':form,
                    'message':'you have already added the album'

                }
                return render(request, 'music/create_album.html',context)
        album=form.save(commit=False)
        album.album_cover=request.FILES['album_cover']
        album.user=request.user
        album.save()
        return render(request,'music/info.html',{'album':album})
    return render(request,'music/create_album.html', {'form':form})

class AlbumUpdateView(UpdateView):
    model=Album
    fields=['album_name','artist_name','artist_genre']
    template='music/create-album.html'

def album_delete(delete,album_id):
    album=get_object_or_404(Album, pk=album_id)
    album.delete()
    return redirect('/')

def create_song(request, album_id):
    form=SongForm(request.POST or None, request.FILES or None)
    album=get_object_or_404(Album,pk=album_id)
    if form.is_valid():
        for s in album.song_set.all():
            if s.song_name== form.cleaned_data.get('song_name'):
                context={
                    'form':form,
                    'message':'You have already added that song'
                }
                return render(request,'music/create_song.html',context
                              )
        song=form.save(commit=False)
        song.album=album
        song.song_audio=request.FILES['song_audio']
        song.save()
        return render(request, 'music/info.html', {'album':album})
    return render(request,'music/create_song.html', {'form':form})

class SongUpdateView(UpdateView):
    model = Song
    fields = ['song_name','song_audio']
    template_name = 'boom/create_song.html'

def delete_song(request,album_id,song_id):
    album=get_object_or_404(Album, pk=album_id)
    song=get_object_or_404(Song, pk=song_id)
    song.delete()
    context={
        'album' : album,
        'message' : 'Song Deleted Successfully!'
    }
    return render(request, 'boom/info.html',context)

def signup(request):
    form=UserForm(request.POST or None)
    if form.is_valid():
        username=form.cleaned_data['username']
        password=form.cleaned_data['password']
        user=form.save(commit=False)
        user.set_password(password)
        user.save()
        user=authenticate(username=username,password=password)
        if user is not None:
            if user.is_active:
                login(request,user)
                return redirect('boom:index')
    return render(request, 'registration/signup.html', {'form':form})

def signin(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(username=username,password=password)
        if user.is_active:
            login(request,user)
            return redirect('boom:index')
    return render(request,'registration/login.html')

def logout_user(request):
    logout(request)
    return redirect('boom:login')

boom/templates/music/base.html
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>

{% load static %}
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'music/css/style.css' %}"/>
</head>

<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'boom:index' %}">Hip-Hop</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'boom:index' %}">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="{%url 'boom:index' %}"><i class="fas fa-headphones"></i> Albums</a></li>
      </ul>

      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" name="q" value="{{request.GET.q}}" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-info">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'boom:create-album' %}"><i class="fas fa-plus-square"></i> Add Album</a></li>
        <li><a href="{% url 'boom:logout-user' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block content %}{% endblock %}
</body>
</html>

boom/templates/music/create_album.html
{% extends 'music/base.html'%}
{% load crispy_forms_tags %}
{% block title %}New Album{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div class="panel panel-success panel-body">
                <h3 class="text-info text-center text-capitalize">{% if update%}update &nbsp;<i class="fas fa-headphones-alt fa-3x"></i>&nbsp;{%else%}Add &nbsp;<i class="fas fa-headphones-alt fa-3x"></i>album{%endif%}</h3>
                <hr>
                <form method="post" enctype="multipart/form-data">
                    {% if message %}
                    <div class="alert alert-danger">
                        <h4 class="text-primary">{{message}}</h4>
                    </div>
                    {%endif%}
                    {%csrf_token%}
                    {{form|crispy}}
                    <button type="btn btn-info" class="btn btn-info">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{%endblock%}

boom/templates/music/create_song.html
{% extends 'music/base.html' %}
{% load crispy_forms_tags %}
{% block title %}New song{%endblock%}
{%block content%}

<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-success" style="background-color:#ccc;">
                <div class="panel-body">
                    <h3 class="text primary text-capitalize">{% if update %}update song{%else%} add song{%endif%}</h3>
                    <form method="post" enctype="multipart/form-data">
                        {%if message%}
                        <div class="alert alert-primary">
                            <h4 class="text-danger">{{message}}</h4>
                        </div>
                        {%endif%}
                        {% csrf_token %}
                        {{form|crispy}}
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

boom/templates/music/index.html
{% extends 'music/base.html' %}
{% block title %}Hip-hop{% endblock %}

{% block content %}
<div class="container-fluid" >
    <div class="row">
        <h5 class="text-success">{{request.user.username}}</h5>
        {% if albums %}
            {% for album in albums %}
                <div class="col-sm-3">
                    <div class="thumbnail" style="background-color:#0000;color:white;">
                        <a href="{%url 'boom:info' album.id%}">
                            <img src="{{album.album_cover.url}}" class="img img-responsive" alt="" style="height:150px; width:80%;">

                        </a>

                        <div class="caption" >
                            <h4>{{album.album_name}}</h4>
                            <h5>{{album.artist_name}}</h5>
                            <a href="{% url 'boom:album-update' album.id%}" class="btn btn-info btn-sm"><i class="fas fa-edit"></i> </a>
                            <a href="{% url 'boom:album-delete' album.id%}" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i> </a>
                        </div>
                    </div>
                </div>


            {%endfor%}
        {%endif%}
    </div>
</div>
{%endblock%}

boom/templates/music/info.html
{% extends 'music/base.html' %}
{% block title %}{{album.album_name}}{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <!--Album info-->
        <div class="col-sm-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <img src="{{album.album_cover.url}}" class="img img-responsive" alt="">
                <div class="caption">
                    <h5>{{album.album_name}}</h5>
                     <h5>{{album.album_genre}}</h5>

                </div>
            </div>
        </div>
        </div>

     <!--song info-->
        <div class="col-sm-9">
        <ul class="nav nav-pills">
            <li class="active"><a href="">Songs</a></li>
            <li><a href="{% url 'boom:create-song' album.id%}">Add Song</a></li>
        </ul>
<div class="panel panel-success" style="margin:2px;">
    <div class="panel-body">

    <h3 class="text-info">Songs</h3>
        <hr>
        <table class="table table-stripe">
            <thead>
            <th>Song Name</th>
            <th>Audio</th>
            <th>favorite</th>
            <th>Action</th>

            </thead>
            <tbody>
            {% if album.song_set%}
                {% for song in album.song_set.all%}
                <tr>
                    <td>{{song.song_name}}</td>
                    <td><a href="{{song.song_audio}}" class="btn btn-info btn-sm" target="_blank"><i class="fas fa-play"></i></a></td>
                    <td><a href="" class="btn btn-warning btn-sm"><i class="fas fa-star"></i></a> </td>
                    <td><a href="{% url 'boom:update-song' song.id %}" class="btn btn-success"><i class="fas fa-edit"></i> </a>
                        <a href="{% url 'boom:song-delete' album.id song.id %}" class="btn btn-danger"><i class="fas fa-trash"></i> </a></td>
                </tr>
                {%endfor%}
            {%endif%}
            </tbody>
        </table>
    </div>
</div>
            </div>
    </div>
</div>
{% endblock %}